kind: pipeline
name: default

steps:
  - name: install
    image: ruby:2.6.1
    volumes:
      - name: bundle
        path: /usr/local/bundle
    commands:
      - gem install bundler -v "~> 2.0.1"
      - bundle install --jobs=3 --retry=3

  - name: test
    image: ruby
    environment:
      CODECOV_TOKEN:
        from_secret: CODECOV_TOKEN
      CI: true
    volumes:
      - name: bundle
        path: /usr/local/bundle
    commands:
      - bundle exec rspec

volumes:
  - name: bundle
    temp: {}
